name: Conventional Commits Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR Commits
        run: |
          PR_COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits" \
          | jq -r '.[].commit.message')
          echo "$PR_COMMITS" > commit_messages.txt

      - name: Validate Commit Messages
        id: commit_validation
        continue-on-error: true
        run: |
          regex="^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\([a-zA-Z0-9-_]+\))?!?: .{1,50}$"
          invalid=false
          echo "Validating commits..."
          while IFS= read -r commit; do
            echo "Validating: $commit"  # Debugging: print commit message
            if ! [[ "$commit" =~ $regex ]]; then
              echo "Invalid commit message: $commit"
              invalid=true
            fi
          done < commit_messages.txt
          if [ "$invalid" = true ]; then
            echo "Commit messages do not follow Conventional Commits format."
            exit 1
          fi

      - name: Close PR if invalid commit messages
        if: steps.commit_validation.outcome == 'failure'
        run: |
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
          -d '{"state": "closed"}'

      - name: Send PR Closure Notification
        if: steps.commit_validation.outcome == 'failure'
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $SENDGRID_API_KEY" \
          --header "Content-Type: application/json" \
          --data '{
            "personalizations": [{
              "to": [{"email": "sselvadurai@dons.usfca.edu"}],
              "subject": "PR Closed Due to Invalid Commits"
            }],
            "from": {"email": "sselvadurai@dons.usfca.edu"},
            "content": [{"type": "text/plain", "value": "Your PR was closed because it did not follow the Conventional Commits format."}]
          }'
