name: Nightly Build

on:
  schedule:
    - cron: '40 2 * * *'  # Runs at 2:40 AM UTC (6:40 PM PST)
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest python-dotenv  # Install python-dotenv to load the .env file

      - name: Load Environment Variables from .env
        run: |
          if [ -f .env ]; then
            echo "Loading environment variables from .env file"
            set -a
            source .env
            set +a
          else
            echo ".env file not found, skipping..."
          fi

      - name: Run Tests
        run: |
          pytest || (echo "Tests failed. Exiting..." && exit 1)

      - name: Log in to Docker Hub
        if: success()
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        if: success()
        run: |
          docker build -t myregistry/fastapi-app:latest .
          docker push myregistry/fastapi-app:latest

      - name: Send Failure Notification if Tests Fail
        if: failure()
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          curl --request POST \
          --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $SENDGRID_API_KEY" \
          --header "Content-Type: application/json" \
          --data '{
            "personalizations": [{
              "to": [{"email": "sselvadurai@dons.usfca.edu"}],
              "subject": "Nightly Build Failed"
            }],
            "from": {"email": "sselvadurai@dons.usfca.edu"},
            "content": [{"type": "text/plain", "value": "Nightly build failed due to test failures."}]
          }'
